### PR TITLE
Transform streaming() method to accept raw streams as well as strings…

### PR DESCRIPTION
**Pull request by Champii**
… path

### CODE REVIEW

**Comment by freewil** [comment]
Awesome, looks good to me 👍 . I'll leave this open for a few days if someone else wants to review it as well.

**Comment by Champii** [comment]
Nice ! Thanks for your review !

I did not complete your current set of methods with helpers like `encryptToStream()` or `encryptStream()`,
It might be a good idea to implement them and make the corresponding doc.
I may wait for you to merge this one as it is blocking for a projet i'm currently working on, and then open a new PR with theses methods.

Are you ok with that ?

**Comment by freewil** [comment]
Yeah, that'd be great.

**Comment by freewil** [comment]
After you add the new methods and doc, I'll do a release

**Comment by Champii** [comment]
Here they are !

**Pull request merged**
